project: /data/benchaaben/DINOv2-3D-Med
run_name: dinov2_finetune_classifier
base_dir: /data/colon_cancer/dinov2_experiments/dinov2_pretrain


max_epochs: 200
patch_size: [160, 160, 160]
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  max_epochs: "%max_epochs"
  log_every_n_steps: 10
  enable_model_summary: True
  logger:
    - _target_: pytorch_lightning.loggers.MLFlowLogger
      experiment_name: dinov2_classifier_finetune
      tracking_uri: "file:/data/colon_cancer/dinov2_experiments/mlruns"
      run_name: "%run_name"  
      tags:
        task: classification
        model: dinov2_3d
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint  
      dirpath: "%run_dir"
      filename: "dinov2_3d_best_{epoch:03d}-{val_loss:.2f}"
      monitor: val_loss
      mode: min
      save_top_k: 1
      save_last: True
      every_n_epochs: 1
      save_on_train_epoch_end: True

lightning_module:
  _target_: project.training.DINOv2ClassifierFinetuner
  num_classes: 2
  lr: !!float 1e-4
  weight_decay: !!float 1e-5
  freeze_backbone_strategy: "never"  # "always" | "first_epochs" | "never"
  freeze_backbone_epochs: 5                 # only relevant if strategy="first_epochs"
  head_hidden_dims: [432, 216, 108]
  head_dropout: 0.1
  pooling: cls
  scheduler_t_max: "%max_epochs"
  input_channels: 2
  backbone:
    _target_: project.utils.load_pretrained_backbone.create_backbone_with_checkpoint
    checkpoint_path: /data/colon_cancer/dinov2_experiments/dinov2_pretrain/__local_refs['run_name']/last.ckpt
    backbone_kwargs:
      embed_dim: 864
      eva_depth: 16
      eva_numheads: 12
      input_channels: 1
      num_classes: 1
      input_shape: "%patch_size"
      patch_embed_size: [8, 8, 8]
      patch_drop_rate: 0.0
      classification: True
      init_values: 0.01
      scale_attn_inner: True
    strict: True
    device: 'cuda:0'

data_module:
  _target_: project.training.data_module_finetune.DataModuleCC
  num_workers: 4
  batch_size: 16
  pin_memory: true

  ds_train:
    _target_: project.configs.datasets.coloncancer.ColonCancer
    dataset_name: Dataset_CC_dummy
    patch_size: "%patch_size"
    num_patches_per_epoch: 2500
    split: "train"
    use_labels: True
    head: classification

  ds_val:
    _target_: project.configs.datasets.coloncancer.ColonCancer
    dataset_name: Dataset_CC_dummy
    patch_size: "%patch_size"
    num_patches_per_epoch: 250
    split: "val"
    use_labels: True 
    head: classification
